- arms: none
- foldedLegs: none
- jumpingjack: none
- legs: none
- shoulders: bronzo
- squat: none
- n_arms: 0
- n_foldedLegs: 0
- n_jumpingjack: 0
- n_legs: 0
- n_shoulders: 0
- n_squat: 0

